### ISSUE TITLE
Watchdog causes VKP, PFA unable to load (solved) + Notes get dropped randomly

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#18]
Dropped notes: https://drive.google.com/open?id=0B-k9O996VHoLQXd4ZXlseWRDem8 (ignore the Necrofantasia part)
VKP unable to load: https://drive.google.com/open?id=0B-k9O996VHoLOG52bVc1YzFHa00 (I already tested this with PFA)

I'll use video proofs more often mostly because I'm lazy to type :)
Off-topic: Did you know why in the first video, only VMS#2 appear and not 1?

**Comment by KaleidonKep99** [comment]
The watchdog system currently doesn't support the ReactOS MIDI Mapper.
Trying to load patched programs will make them hang at startup.
I'm already working on this.

For the dropped notes, I don't have this problem... Are you sure your voices are higher than 400, and that the max CPU usage is higher than 40-45%?

**Comment by KaleidonKep99** [comment]
I fixed the watchdog issue with ReactOS with [release 3.3.1.8](https://github.com/KaleidonKep99/Keppy-s-Driver/releases/tag/3.3.1.8).

**Comment by longnguyen2004** [comment]
My voice limit is at 1000 and CPU limit is 100%. I have that exact settings in VMS.

**Comment by KaleidonKep99** [comment]
Set the CPU limit to 75% btw, and uncheck "Only release the oldest instance upon a note off event when there are overlapping instances of the notes".

**Comment by longnguyen2004** [comment]
Ok, I'll try later

**Comment by longnguyen2004** [comment]
It still doesn't work: https://drive.google.com/open?id=0B-k9O996VHoLSFAwbU1KN2g0UDA

**Comment by KaleidonKep99** [comment]
Can I have the MIDI please?
I guess it's something with ReactOS and it's WinMM system. (Since you're using its files)

**Comment by KaleidonKep99** [comment]
Oops I accidentally closed it...

**Comment by longnguyen2004** [comment]
Here: https://drive.google.com/open?id=0B-k9O996VHoLNlBoYWlFMlctdGs

**Comment by KaleidonKep99** [comment]
It works just fine for me: https://drive.google.com/open?id=0B05Sp4zxPFR6MEJWZzY1cFF4VVk

I recommend to set the frequency to something higher than 32000Hz, for the sake of audio quality.

**Comment by longnguyen2004** [comment]
ok

EDIT: Still doesn't work

**Comment by longnguyen2004** [comment]
I'll try DirectSound mode tomorrow to see if there's any changes

**Comment by longnguyen2004** [comment]
Since I tried everything but it still doesn't fix the problem, I'll just use VMS for replacement.
P.S: It look like each MIDIs have a completely muted channel only at some specific time. Unbounded 2 have channel 7 muted after the intro,...

**Comment by KaleidonKep99** [comment]
Did you try a different soundfont?

**Comment by longnguyen2004** [comment]
I tried TASCAM CVPiano, Fazioli Grand, Roland Fantasy,... but still doesn't work.

**Comment by KaleidonKep99** [comment]
I really don't know then, because it works just fine for me.

Have you tried reinstalling Keppy's Driver? (Uninstall and install)

**Comment by longnguyen2004** [comment]
Also tried but no success.
I'll try release 3.3.0.1 which doesn't have the mixer stuff.

**Comment by KaleidonKep99** [comment]
Try using [3.3.2.1](https://github.com/KaleidonKep99/Keppy-s-Driver/releases/tag/3.3.2.1).

**Comment by longnguyen2004** [comment]
It looks like that only VKP have this issue. I tested with PFA and it plays just fine. So it's probably a VKP issue.

**Comment by KaleidonKep99** [comment]
You could try using TMIDI.

Anyway, since it's not something with Keppy's Driver, I'll just close this.
